---
name: commland-application-external-websites
base_branch: origin/master
exposure: private
metapackage:
  - name: meta-commland
    branch: master
    package: commland-application-external-websites
    type: required
base_core:
template: commland-application.spec.tmpl
package:
  centos7:
    name: commland-application-external-websites
    summary: comm.land Application - external-websites
    app_name: external-websites
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: http://www.2600hz.org/
    vendor: 2600Hz
